// Code generated by go-swagger; DO NOT EDIT.

package webhook

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kelvintaywl/circleci-webhook-go-sdk/models"
)

// GetWebhookReader is a Reader for the GetWebhook structure.
type GetWebhookReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetWebhookReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetWebhookOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetWebhookBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetWebhookOK creates a GetWebhookOK with default headers values
func NewGetWebhookOK() *GetWebhookOK {
	return &GetWebhookOK{}
}

/*
GetWebhookOK describes a response with status code 200, with default header values.

A webhook
*/
type GetWebhookOK struct {
	Payload *models.WebhookInfo
}

// IsSuccess returns true when this get webhook o k response has a 2xx status code
func (o *GetWebhookOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get webhook o k response has a 3xx status code
func (o *GetWebhookOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get webhook o k response has a 4xx status code
func (o *GetWebhookOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get webhook o k response has a 5xx status code
func (o *GetWebhookOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get webhook o k response a status code equal to that given
func (o *GetWebhookOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetWebhookOK) Error() string {
	return fmt.Sprintf("[GET /webhook/{id}][%d] getWebhookOK  %+v", 200, o.Payload)
}

func (o *GetWebhookOK) String() string {
	return fmt.Sprintf("[GET /webhook/{id}][%d] getWebhookOK  %+v", 200, o.Payload)
}

func (o *GetWebhookOK) GetPayload() *models.WebhookInfo {
	return o.Payload
}

func (o *GetWebhookOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.WebhookInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetWebhookBadRequest creates a GetWebhookBadRequest with default headers values
func NewGetWebhookBadRequest() *GetWebhookBadRequest {
	return &GetWebhookBadRequest{}
}

/*
GetWebhookBadRequest describes a response with status code 400, with default header values.

Invalid input
*/
type GetWebhookBadRequest struct {
	Payload *models.Errored
}

// IsSuccess returns true when this get webhook bad request response has a 2xx status code
func (o *GetWebhookBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get webhook bad request response has a 3xx status code
func (o *GetWebhookBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get webhook bad request response has a 4xx status code
func (o *GetWebhookBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get webhook bad request response has a 5xx status code
func (o *GetWebhookBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get webhook bad request response a status code equal to that given
func (o *GetWebhookBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *GetWebhookBadRequest) Error() string {
	return fmt.Sprintf("[GET /webhook/{id}][%d] getWebhookBadRequest  %+v", 400, o.Payload)
}

func (o *GetWebhookBadRequest) String() string {
	return fmt.Sprintf("[GET /webhook/{id}][%d] getWebhookBadRequest  %+v", 400, o.Payload)
}

func (o *GetWebhookBadRequest) GetPayload() *models.Errored {
	return o.Payload
}

func (o *GetWebhookBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Errored)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
