// Code generated by go-swagger; DO NOT EDIT.

package webhook

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kelvintaywl/circleci-webhook-go-sdk/models"
)

// ListWebhooksReader is a Reader for the ListWebhooks structure.
type ListWebhooksReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListWebhooksReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListWebhooksOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListWebhooksBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListWebhooksOK creates a ListWebhooksOK with default headers values
func NewListWebhooksOK() *ListWebhooksOK {
	return &ListWebhooksOK{}
}

/*
ListWebhooksOK describes a response with status code 200, with default header values.

A list of webhooks
*/
type ListWebhooksOK struct {
	Payload *models.WebhooksInfo
}

// IsSuccess returns true when this list webhooks o k response has a 2xx status code
func (o *ListWebhooksOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list webhooks o k response has a 3xx status code
func (o *ListWebhooksOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list webhooks o k response has a 4xx status code
func (o *ListWebhooksOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list webhooks o k response has a 5xx status code
func (o *ListWebhooksOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list webhooks o k response a status code equal to that given
func (o *ListWebhooksOK) IsCode(code int) bool {
	return code == 200
}

func (o *ListWebhooksOK) Error() string {
	return fmt.Sprintf("[GET /webhook][%d] listWebhooksOK  %+v", 200, o.Payload)
}

func (o *ListWebhooksOK) String() string {
	return fmt.Sprintf("[GET /webhook][%d] listWebhooksOK  %+v", 200, o.Payload)
}

func (o *ListWebhooksOK) GetPayload() *models.WebhooksInfo {
	return o.Payload
}

func (o *ListWebhooksOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.WebhooksInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListWebhooksBadRequest creates a ListWebhooksBadRequest with default headers values
func NewListWebhooksBadRequest() *ListWebhooksBadRequest {
	return &ListWebhooksBadRequest{}
}

/*
ListWebhooksBadRequest describes a response with status code 400, with default header values.

Invalid input
*/
type ListWebhooksBadRequest struct {
	Payload *models.Errored
}

// IsSuccess returns true when this list webhooks bad request response has a 2xx status code
func (o *ListWebhooksBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list webhooks bad request response has a 3xx status code
func (o *ListWebhooksBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list webhooks bad request response has a 4xx status code
func (o *ListWebhooksBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this list webhooks bad request response has a 5xx status code
func (o *ListWebhooksBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this list webhooks bad request response a status code equal to that given
func (o *ListWebhooksBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *ListWebhooksBadRequest) Error() string {
	return fmt.Sprintf("[GET /webhook][%d] listWebhooksBadRequest  %+v", 400, o.Payload)
}

func (o *ListWebhooksBadRequest) String() string {
	return fmt.Sprintf("[GET /webhook][%d] listWebhooksBadRequest  %+v", 400, o.Payload)
}

func (o *ListWebhooksBadRequest) GetPayload() *models.Errored {
	return o.Payload
}

func (o *ListWebhooksBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Errored)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
