// Code generated by go-swagger; DO NOT EDIT.

package webhook

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kelvintaywl/circleci-webhook-go-sdk/models"
)

// NewUpdateWebhookParams creates a new UpdateWebhookParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateWebhookParams() *UpdateWebhookParams {
	return &UpdateWebhookParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateWebhookParamsWithTimeout creates a new UpdateWebhookParams object
// with the ability to set a timeout on a request.
func NewUpdateWebhookParamsWithTimeout(timeout time.Duration) *UpdateWebhookParams {
	return &UpdateWebhookParams{
		timeout: timeout,
	}
}

// NewUpdateWebhookParamsWithContext creates a new UpdateWebhookParams object
// with the ability to set a context for a request.
func NewUpdateWebhookParamsWithContext(ctx context.Context) *UpdateWebhookParams {
	return &UpdateWebhookParams{
		Context: ctx,
	}
}

// NewUpdateWebhookParamsWithHTTPClient creates a new UpdateWebhookParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateWebhookParamsWithHTTPClient(client *http.Client) *UpdateWebhookParams {
	return &UpdateWebhookParams{
		HTTPClient: client,
	}
}

/*
UpdateWebhookParams contains all the parameters to send to the API endpoint

	for the update webhook operation.

	Typically these are written to a http.Request.
*/
type UpdateWebhookParams struct {

	/* Body.

	   Webhook information (payload)
	*/
	Body *models.WebhookPayload

	/* ID.

	   ID of the webhook

	   Format: uuid
	*/
	ID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update webhook params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateWebhookParams) WithDefaults() *UpdateWebhookParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update webhook params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateWebhookParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update webhook params
func (o *UpdateWebhookParams) WithTimeout(timeout time.Duration) *UpdateWebhookParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update webhook params
func (o *UpdateWebhookParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update webhook params
func (o *UpdateWebhookParams) WithContext(ctx context.Context) *UpdateWebhookParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update webhook params
func (o *UpdateWebhookParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update webhook params
func (o *UpdateWebhookParams) WithHTTPClient(client *http.Client) *UpdateWebhookParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update webhook params
func (o *UpdateWebhookParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update webhook params
func (o *UpdateWebhookParams) WithBody(body *models.WebhookPayload) *UpdateWebhookParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update webhook params
func (o *UpdateWebhookParams) SetBody(body *models.WebhookPayload) {
	o.Body = body
}

// WithID adds the id to the update webhook params
func (o *UpdateWebhookParams) WithID(id strfmt.UUID) *UpdateWebhookParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update webhook params
func (o *UpdateWebhookParams) SetID(id strfmt.UUID) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateWebhookParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
