// Code generated by go-swagger; DO NOT EDIT.

package webhook

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new webhook API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for webhook API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	DeleteWebhook(params *DeleteWebhookParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteWebhookOK, error)

	GetWebhook(params *GetWebhookParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetWebhookOK, error)

	UpdateWebhook(params *UpdateWebhookParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*UpdateWebhookOK, error)

	AddWebhook(params *AddWebhookParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*AddWebhookCreated, error)

	ListWebhooks(params *ListWebhooksParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListWebhooksOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
DeleteWebhook deletes a webhook
*/
func (a *Client) DeleteWebhook(params *DeleteWebhookParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteWebhookOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteWebhookParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DeleteWebhook",
		Method:             "DELETE",
		PathPattern:        "/webhook/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DeleteWebhookReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteWebhookOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for DeleteWebhook: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetWebhook gets a webhook

Get a webhook by id
*/
func (a *Client) GetWebhook(params *GetWebhookParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetWebhookOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetWebhookParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetWebhook",
		Method:             "GET",
		PathPattern:        "/webhook/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetWebhookReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetWebhookOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetWebhook: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
UpdateWebhook updates a webhook
*/
func (a *Client) UpdateWebhook(params *UpdateWebhookParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*UpdateWebhookOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUpdateWebhookParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "UpdateWebhook",
		Method:             "PUT",
		PathPattern:        "/webhook/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &UpdateWebhookReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*UpdateWebhookOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for UpdateWebhook: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
AddWebhook adds a new webhook
*/
func (a *Client) AddWebhook(params *AddWebhookParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*AddWebhookCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewAddWebhookParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "addWebhook",
		Method:             "POST",
		PathPattern:        "/webhook",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &AddWebhookReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*AddWebhookCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for addWebhook: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
ListWebhooks lists webhooks

Get a list of webhook that match the given scope-type and scope-id
*/
func (a *Client) ListWebhooks(params *ListWebhooksParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListWebhooksOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListWebhooksParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "listWebhooks",
		Method:             "GET",
		PathPattern:        "/webhook",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ListWebhooksReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ListWebhooksOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for listWebhooks: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
