// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// WebhookInfo webhook info
//
// swagger:model WebhookInfo
type WebhookInfo struct {
	WebhookPayload

	// The date and time the webhook was last updated
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"created-at,omitempty"`

	// The unique ID of the webhook
	// Format: uuid
	ID strfmt.UUID `json:"id,omitempty"`

	// The date and time the webhook was created
	// Format: date-time
	UpdatedAt strfmt.DateTime `json:"updated-at,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *WebhookInfo) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 WebhookPayload
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.WebhookPayload = aO0

	// AO1
	var dataAO1 struct {
		CreatedAt strfmt.DateTime `json:"created-at,omitempty"`

		ID strfmt.UUID `json:"id,omitempty"`

		UpdatedAt strfmt.DateTime `json:"updated-at,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.CreatedAt = dataAO1.CreatedAt

	m.ID = dataAO1.ID

	m.UpdatedAt = dataAO1.UpdatedAt

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m WebhookInfo) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.WebhookPayload)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)
	var dataAO1 struct {
		CreatedAt strfmt.DateTime `json:"created-at,omitempty"`

		ID strfmt.UUID `json:"id,omitempty"`

		UpdatedAt strfmt.DateTime `json:"updated-at,omitempty"`
	}

	dataAO1.CreatedAt = m.CreatedAt

	dataAO1.ID = m.ID

	dataAO1.UpdatedAt = m.UpdatedAt

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this webhook info
func (m *WebhookInfo) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with WebhookPayload
	if err := m.WebhookPayload.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdatedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WebhookInfo) validateCreatedAt(formats strfmt.Registry) error {

	if swag.IsZero(m.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("created-at", "body", "date-time", m.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *WebhookInfo) validateID(formats strfmt.Registry) error {

	if swag.IsZero(m.ID) { // not required
		return nil
	}

	if err := validate.FormatOf("id", "body", "uuid", m.ID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *WebhookInfo) validateUpdatedAt(formats strfmt.Registry) error {

	if swag.IsZero(m.UpdatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("updated-at", "body", "date-time", m.UpdatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this webhook info based on the context it is used
func (m *WebhookInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with WebhookPayload
	if err := m.WebhookPayload.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *WebhookInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WebhookInfo) UnmarshalBinary(b []byte) error {
	var res WebhookInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
