// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// WebhookPayload webhook payload
//
// swagger:model WebhookPayload
type WebhookPayload struct {

	// Events that will trigger the webhook
	Events []string `json:"events"`

	// Name of the webhook
	Name string `json:"name,omitempty"`

	// scope
	Scope *WebhookPayloadScope `json:"scope,omitempty"`

	// Secret used to build an HMAC hash of the payload and passed as a header in the webhook request
	SigningSecret string `json:"signing-secret,omitempty"`

	// URL to deliver the webhook to. Note: protocol must be included as well (only https is supported)
	URL string `json:"url,omitempty"`

	// Whether to enforce TLS certificate verification when delivering the webhook
	VerifyTLS bool `json:"verify-tls,omitempty"`
}

// Validate validates this webhook payload
func (m *WebhookPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEvents(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateScope(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var webhookPayloadEventsItemsEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["workflow-completed","job-completed"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		webhookPayloadEventsItemsEnum = append(webhookPayloadEventsItemsEnum, v)
	}
}

func (m *WebhookPayload) validateEventsItemsEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, webhookPayloadEventsItemsEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *WebhookPayload) validateEvents(formats strfmt.Registry) error {
	if swag.IsZero(m.Events) { // not required
		return nil
	}

	for i := 0; i < len(m.Events); i++ {

		// value enum
		if err := m.validateEventsItemsEnum("events"+"."+strconv.Itoa(i), "body", m.Events[i]); err != nil {
			return err
		}

	}

	return nil
}

func (m *WebhookPayload) validateScope(formats strfmt.Registry) error {
	if swag.IsZero(m.Scope) { // not required
		return nil
	}

	if m.Scope != nil {
		if err := m.Scope.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("scope")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("scope")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this webhook payload based on the context it is used
func (m *WebhookPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateScope(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WebhookPayload) contextValidateScope(ctx context.Context, formats strfmt.Registry) error {

	if m.Scope != nil {
		if err := m.Scope.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("scope")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("scope")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *WebhookPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WebhookPayload) UnmarshalBinary(b []byte) error {
	var res WebhookPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// WebhookPayloadScope The scope in which the relevant events that will trigger webhooks
//
// swagger:model WebhookPayloadScope
type WebhookPayloadScope struct {

	// ID of the scope being used (at the moment, only project ID is supported)
	// Format: uuid
	ID strfmt.UUID `json:"id,omitempty"`

	// Type of the scope being used
	Type *string `json:"type,omitempty"`
}

// Validate validates this webhook payload scope
func (m *WebhookPayloadScope) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WebhookPayloadScope) validateID(formats strfmt.Registry) error {
	if swag.IsZero(m.ID) { // not required
		return nil
	}

	if err := validate.FormatOf("scope"+"."+"id", "body", "uuid", m.ID.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this webhook payload scope based on context it is used
func (m *WebhookPayloadScope) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WebhookPayloadScope) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WebhookPayloadScope) UnmarshalBinary(b []byte) error {
	var res WebhookPayloadScope
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
